/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Egresados;

import Capacitaciones.Metodos_capacitacion;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import metodos.Metodoss;

/**
 *
 * @author anton
 */
public class frmReporteTotal extends javax.swing.JFrame {
    SimpleDateFormat formato_fecha = new SimpleDateFormat("yyyy-MM-dd");
    Metodoss m = new Metodoss();
    Metodos_capacitacion ejecutar= new Metodos_capacitacion();
    public frmReporteTotal() {
        initComponents();
        llenarCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbx_C_consulta = new javax.swing.JComboBox<>();
        cbx_area = new javax.swing.JComboBox<>();
        cbx_especializacion = new javax.swing.JComboBox<>();
        lbl_cAsistencias_CAPA = new javax.swing.JLabel();
        jdc_FechaFin = new com.toedter.calendar.JDateChooser();
        jdc_FechaInicio = new com.toedter.calendar.JDateChooser();
        btn_Buscar = new javax.swing.JButton();
        lbl_id_CAPA = new javax.swing.JLabel();
        lbl_NOMBRE_CAPA = new javax.swing.JLabel();
        lbl_MONTO_CAPA = new javax.swing.JLabel();
        lbl_MODALIDAD_CAPA = new javax.swing.JLabel();
        lbl_cInvitaciones_CAPA = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ckx_especialidad = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CAPACITACIONES"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("FECHA INICIO:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel1.setText("FECHA FIN:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        cbx_C_consulta.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        cbx_C_consulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "% ASISTENCIAS MAYOR", "% ASISTENCIAS MENOR" }));
        cbx_C_consulta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        cbx_C_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_C_consultaActionPerformed(evt);
            }
        });
        jPanel2.add(cbx_C_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, 50));

        cbx_area.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        cbx_area.setToolTipText("");
        cbx_area.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbx_area.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbx_area.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cbx_area.setEnabled(false);
        cbx_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_areaActionPerformed(evt);
            }
        });
        jPanel2.add(cbx_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 180, 50));

        cbx_especializacion.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        cbx_especializacion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        cbx_especializacion.setEnabled(false);
        cbx_especializacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_especializacionActionPerformed(evt);
            }
        });
        jPanel2.add(cbx_especializacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 180, 50));

        lbl_cAsistencias_CAPA.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPanel2.add(lbl_cAsistencias_CAPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 70, 20));

        jdc_FechaFin.setBackground(new java.awt.Color(255, 255, 255));
        jdc_FechaFin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jdc_FechaFin.setDateFormatString("yyyy-MM-dd");
        jdc_FechaFin.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jPanel2.add(jdc_FechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 160, 50));

        jdc_FechaInicio.setBackground(new java.awt.Color(255, 255, 255));
        jdc_FechaInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jdc_FechaInicio.setDateFormatString("yyyy-MM-dd");
        jdc_FechaInicio.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jPanel2.add(jdc_FechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 50));

        btn_Buscar.setBackground(new java.awt.Color(255, 51, 51));
        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 50, 50));

        lbl_id_CAPA.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPanel2.add(lbl_id_CAPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 70, 20));

        lbl_NOMBRE_CAPA.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPanel2.add(lbl_NOMBRE_CAPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 220, 20));

        lbl_MONTO_CAPA.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPanel2.add(lbl_MONTO_CAPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 70, 20));

        lbl_MODALIDAD_CAPA.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPanel2.add(lbl_MODALIDAD_CAPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 70, 20));

        lbl_cInvitaciones_CAPA.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPanel2.add(lbl_cInvitaciones_CAPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 70, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setText("C. Asistentes:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setText("ID:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setText("Nombre:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel8.setText("Costo:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel9.setText("Modalidad:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel10.setText("C. Invitados:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        ckx_especialidad.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ckx_especialidad.setText("ESPECIALIDAD");
        ckx_especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckx_especialidadActionPerformed(evt);
            }
        });
        jPanel2.add(ckx_especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 600, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_areaActionPerformed
        DefaultComboBoxModel<String> modelo;
        String Texto_Seleccionado = cbx_area.getSelectedItem().toString();
        int area=cbx_area.getSelectedIndex();
        if(area==0){
            modelo= new DefaultComboBoxModel<>();
            cbx_especializacion.setModel(modelo);
            cbx_especializacion.setEnabled(false);
        }else{
            int id=m.obtener_id_Area_trabajo(Texto_Seleccionado);
            modelo = ejecutar.obtener_especializaciones(id);
            cbx_especializacion.setModel(modelo);
            cbx_especializacion.setEnabled(true);
        }
    }//GEN-LAST:event_cbx_areaActionPerformed

    private void cbx_especializacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_especializacionActionPerformed
//        DefaultComboBoxModel<String> modelo;
//        if(btnCrearActivo){
//            modelo=new DefaultComboBoxModel<>(new String[]{""});
//            cbx_titulo.setEnabled(false);
//        }else {
//            String especializacion_Seleccionada = cbx_especializacion.getSelectedItem().toString();
//            String area_seleccionada=cbx_area.getSelectedItem().toString();
//            modelo = ejecutar.obtener_Titulos(area_seleccionada, especializacion_Seleccionada);
//            cbx_titulo.setModel(modelo);
//            cbx_titulo.setEnabled(true);
//        }
    }//GEN-LAST:event_cbx_especializacionActionPerformed

    private void cbx_C_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_C_consultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_C_consultaActionPerformed

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        String Fecha_I=formato_fecha.format(jdc_FechaInicio.getDate());
        String Fecha_F=formato_fecha.format(jdc_FechaFin.getDate());
        
        String[] detalles_capa = new String[6];
        
        int num = cbx_C_consulta.getSelectedIndex();
        
        if (ckx_especialidad.isSelected()) {
            String area = cbx_area.getSelectedItem().toString();
            String espe = cbx_especializacion.getSelectedItem().toString();
            if(area!=null){
                if(espe!=null){
                    if (num==0){
                    detalles_capa = m.CapaMayorAsistEspe(Fecha_I, Fecha_F, area, espe);
                    lbl_id_CAPA.setText(detalles_capa[0]);
                    lbl_NOMBRE_CAPA.setText(detalles_capa[1]);
                    lbl_MONTO_CAPA.setText(detalles_capa[2]);
                    lbl_MODALIDAD_CAPA.setText(detalles_capa[3]);
                    lbl_cInvitaciones_CAPA.setText(detalles_capa[4]);
                    lbl_cAsistencias_CAPA.setText(detalles_capa[5]);
                    }
                    else if(num==1){
                        detalles_capa = m.CapaMenorAsistEspe(Fecha_I, Fecha_F, area, espe);
                        lbl_id_CAPA.setText(detalles_capa[0]);
                        lbl_NOMBRE_CAPA.setText(detalles_capa[1]);
                        lbl_MONTO_CAPA.setText(detalles_capa[2]);
                        lbl_MODALIDAD_CAPA.setText(detalles_capa[3]);
                        lbl_cInvitaciones_CAPA.setText(detalles_capa[4]);
                        lbl_cAsistencias_CAPA.setText(detalles_capa[5]);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Seleccione una especialización.", "Error", JOptionPane.WARNING_MESSAGE);
                }
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Seleccione una área.", "Error", JOptionPane.WARNING_MESSAGE);
            }
            
        }
        else{
            if (num==0){
                detalles_capa = m.CapaMayorAsist(Fecha_I, Fecha_F);
                lbl_id_CAPA.setText(detalles_capa[0]);
                lbl_NOMBRE_CAPA.setText(detalles_capa[1]);
                lbl_MONTO_CAPA.setText(detalles_capa[2]);
                lbl_MODALIDAD_CAPA.setText(detalles_capa[3]);
                lbl_cInvitaciones_CAPA.setText(detalles_capa[4]);
                lbl_cAsistencias_CAPA.setText(detalles_capa[5]);
            }
            else if(num==1){
                detalles_capa = m.CapaMenorAsist(Fecha_I, Fecha_F);
                lbl_id_CAPA.setText(detalles_capa[0]);
                lbl_NOMBRE_CAPA.setText(detalles_capa[1]);
                lbl_MONTO_CAPA.setText(detalles_capa[2]);
                lbl_MODALIDAD_CAPA.setText(detalles_capa[3]);
                lbl_cInvitaciones_CAPA.setText(detalles_capa[4]);
                lbl_cAsistencias_CAPA.setText(detalles_capa[5]);
            }
        }
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void ckx_especialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckx_especialidadActionPerformed
        if (ckx_especialidad.isSelected()) {
            cbx_area.setEnabled(true);
        }
        else if(ckx_especialidad.isSelected()==false){
            cbx_area.setEnabled(false);
            cbx_especializacion.setEnabled(false);
        }
    }//GEN-LAST:event_ckx_especialidadActionPerformed
    
    private void llenarCombobox() {
        DefaultComboBoxModel<String> model5 = m.obtener_areas_trabajo();
        cbx_area.setModel(model5);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporteTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporteTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporteTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporteTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReporteTotal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JComboBox<String> cbx_C_consulta;
    private javax.swing.JComboBox<String> cbx_area;
    private javax.swing.JComboBox<String> cbx_especializacion;
    private javax.swing.JCheckBox ckx_especialidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser jdc_FechaFin;
    private com.toedter.calendar.JDateChooser jdc_FechaInicio;
    private javax.swing.JLabel lbl_MODALIDAD_CAPA;
    private javax.swing.JLabel lbl_MONTO_CAPA;
    private javax.swing.JLabel lbl_NOMBRE_CAPA;
    private javax.swing.JLabel lbl_cAsistencias_CAPA;
    private javax.swing.JLabel lbl_cInvitaciones_CAPA;
    private javax.swing.JLabel lbl_id_CAPA;
    // End of variables declaration//GEN-END:variables
}
